apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: trunk-recorder-config
    files:
      - configs/config.json
      - configs/talkgroups.csv
resources:
  - pvc.yml
  - deployment.yml
