apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trunk-recorder
  labels:
    app: trunk-recorder
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi