FROM ubuntu:jammy
ENV DEBIAN_FRONTEND=noninteractive
COPY --chmod=0755 entrypoint.sh /entrypoint.sh
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates=20230311ubuntu0.22.04.1 \
        curl=7.81.0-1ubuntu1.16 \
        tigervnc-standalone-server=1.12.0+dfsg-4ubuntu0.22.04.1 \
        tigervnc-xorg-extension=1.12.0+dfsg-4ubuntu0.22.04.1 \
        xterm=372-1ubuntu1 \
        gqrx-sdr=2.15.8-1build1 \
        pulseaudio=1:15.99.1+dfsg1-1ubuntu2.2 \
        xfce4=4.16 \
        dbus-x11=1.12.20-2ubuntu4.1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Slice for websockify  | tar -xz --strip 1 -C /websockify
RUN curl -# -L https://github.com/novnc/websockify/archive/refs/tags/v0.11.0.tar.gz -o /websockify.tar.gz \
    && mkdir /websockify \
    && tar -xz --strip 1 -C /websockify -f /websockify.tar.gz \
    && rm /websockify.tar.gz
ENTRYPOINT [ "/entrypoint.sh" ]