FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
COPY --chmod=0755 entrypoint.sh /entrypoint.sh
RUN apt-get update \
    && apt-get install -y tigervnc-standalone-server=1.12.0+dfsg-4 tigervnc-xorg-extension=1.12.0+dfsg-4 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENTRYPOINT [ "/entrypoint.sh" ]