FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y tigervnc-standalone-server tigervnc-xorg-extension \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && chmod +x /entrypoint.sh
ENTRYPOINT [ "/entrypoint.sh" ]
