FROM node:20 AS novnc-build
ARG NOVNC_VERSION=1.4.0
ARG NOVNC_URL=https://github.com/novnc/noVNC/archive/refs/tags/v${NOVNC_VERSION}.tar.gz
ARG WEBSOCKIFY_URL=https://github.com/novnc/websockify/archive/refs/tags/v0.11.0.tar.gz
ENV DEBIAN_FRONTEND=noninteractive
COPY --chmod=0755 entrypoint.sh /entrypoint.sh
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl=7.81.0-1ubuntu1.16 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /noVNC \
    && curl -# -L ${NOVNC_URL} | tar -xz --strip 1 -C /noVNC
ENTRYPOINT [ "/entrypoint.sh" ]