name: Build and publish the VNC container
on:
  push:
    branches:
      - main
    paths:
      - 'vnc/**'
      - '.github/workflows/vnc.yml'
jobs:
  vnc-server:
    name: Build and publish the VNC server container
    uses: ./.github/workflows/container.yml
    with:
      image: vnc-server
      context: vnc/server
      tag: "1"
  vnc-web:
    name: Build and publish the VNC web container
    uses: ./.github/workflows/container.yml
    with:
      image: vnc-web
      context: vnc/web
      tag: "1"