name: GUI Container Workflow

on:
  push:
    paths:
        - .github/workflows/xorg.yml
        - 'xorg/container/**'

env:
  CONTAINER_CONTEXT: "./xorg/container/"
  CONTAINER_FILE: Containerfile

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Containerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ env.CONTAINER_CONTEXT }}/${{ env.CONTAINER_FILE }}
          format: json
          no-fail: true
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Container Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTAINER_CONTEXT }}
          file: ${{ env.CONTAINER_CONTEXT }}/${{ env.CONTAINER_FILE }}
          push: true
          tags: ghcr.io/hsoj/hamenv:xorg-${{ github.run_id }}